# Generated by Django 4.1.11 on 2023-09-11 02:35

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=djongo.storage.GridFSStorage(
                            base_url="mongodb://localhost:27017filesdb/",
                            collection="videosCollection",
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
