# Generated by Django 4.1.11 on 2023-10-22 01:32

import djongo.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MP3",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(
                        storage=djongo.storage.GridFSStorage(
                            base_url="mongodb://host.minikube.internal:27017/mp3sdb/",
                            collection="mp3sCollection",
                            database="mp3s_db",
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Videos",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(
                        storage=djongo.storage.GridFSStorage(
                            base_url="mongodb://host.minikube.internal:27017/filesdb/",
                            collection="videosCollection",
                            database="videos_db",
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
