# Generated by Django 4.1.11 on 2023-09-28 19:53

import djongo.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MP3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=djongo.storage.GridFSStorage(
                            base_url="mongodb://host.minikube.internal:27017/filesdb/",
                            collection="videosCollection",
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=djongo.storage.GridFSStorage(
                            base_url="mongodb://host.minikube.internal:27017/filesdb/",
                            collection="videosCollection",
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
