# Generated by Django 4.1.11 on 2023-10-19 16:33

import djongo.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mp3",
            name="file",
            field=models.FileField(
                storage=djongo.storage.GridFSStorage(
                    base_url="mongodb://host.minikube.internal:27017/mp3sdb/",
                    collection="mp3sCollection",
                    database="mp3s_db",
                ),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="videos",
            name="file",
            field=models.FileField(
                storage=djongo.storage.GridFSStorage(
                    base_url="mongodb://host.minikube.internal:27017/filesdb/",
                    collection="videosCollection",
                    database="videos_db",
                ),
                upload_to="",
            ),
        ),
    ]
